# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f1519392a4fb1b86887e075f9e119ad2dda1766322861c018718c9ddf8a286e0dd0227a7eb3ec4b4f8762493f3dc7424c286803085ddd76d1d77ef21deebf30

test:
  secret_key_base: f26ad6eec444ec8fdbf0c8c91ab2bcd4e114142d690c52e123ee986d6e9b364a58146e58cd571e30e6f41aa2d2d407982a1f8f4a2be6857f6473c8ebdf0c253c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
